name: Check

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    runs-on: native
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run checks
        env:
          PATH: /run/current-system/sw/bin:/usr/bin:/bin:/usr/local/bin
        run: |
          set -euo pipefail
          nix flake check --accept-flake-config \
            --extra-substituters https://helium-nix.cachix.org \
            --trusted-public-keys helium-nix.cachix.org-1:a8YPjt9O4GPyX0u3gjg/aWpb14teU9aRiSG/MOaSFgw=
